class Loops {
  public static void main(String args[]) {
    for (int i = 0; i < 5; i++) {
      System.out.println("Difference between Loops");
    }
  }
}

//SIMILARITY BETWEEN FOR AND WHILE LOOP
/*
- BOTH ARE ENTRY CONTROLLED LOOPS
- BOTH DONT RUN EVEN ONCE IF THE CONDITION IS LESS THAN 0
*/

//DIFFERENCE BETWEEN FOR AND DO WHILE
/*
- FOR IS ENTRY CONTROLLED, DO WHILE IS EXIT CONTROLLED
- FOR WILL NOT RUN EVEN ONCE IF THE CONDITION IS 0, DO WHILE WILL RUN EVEN IF THE CONDITION IS 0
- FOR CHECKS FOR THE CONDITION FIRST, DO WHILE CHECKS FOR THE CONDITION AFTER THE LOOP IS EXECUTED
*/
